server:
  port: 3000

db:
  type: 'mysql'
  port: 13357
  database: 'new_geisa'
  host: '172.17.60.67'
  # host: '36.86.63.187'
  username: 'uje'
  password: 'ujegeisa'
  # port: 3631
  # database: 'geisa'
  # host: '128.199.148.246'
  # username: 'geisa'
  # password: 'GEISAjaya55'
  synchronize: false

jwt:
  expiresIn: 86400
  secret: '$d3wRm2VXk2ePaZ'

mailer:
  smtp: 'smtp://noreply.opstore@gmail.com:4iDT00Vh@smtp.gmail.com'

upload:
  path: 'public/uploads'
  profilePicPath: 'public/uploads/pp'

prefix:
  frontend: ''
  backend: 'api'
